web:
  image: nginx:1.9
  ports:
    - 6088:5000
  links:
    - app:app
  volumes:
    - ./nginx:/etc/nginx
    - /etc/docker/tls/server-cert.pem:/etc/ssl/certs/docker-registry
    - /etc/docker/tls/server-key.pem:/etc/ssl/private/docker-registry
app:
  image: registry:0.9.1
  links:
    - cache:cache
  volumes_from:
    - data
  environment:
    SETTINGS_FLAVOR: local
    SEARCH_BACKEND: sqlalchemy
    STORAGE_PATH: /data/registry
    CACHE_REDIS_HOST: cache
    CACHE_REDIS_PORT: 6379
    CACHE_LRU_REDIS_HOST: cache
    CACHE_LRU_REDIS_PORT: 6379
    GUNICORN_OPTS: "[--preload]"
cache:
  image: redis:2.6
data:
  image: cogniteev/echo
  volumes:
   - /data/registry
