version: '3'

services:
  web:
    image: nginx:1.15.12-alpine
    ports:
      - 6088:5000
    volumes:
      - ./nginx:/etc/nginx
      - /etc/docker/tls/server-cert.pem:/etc/ssl/certs/docker-registry
      - /etc/docker/tls/server-key.pem:/etc/ssl/private/docker-registry

  app:
    image: registry:2.7.1
    volumes:
      - registry-data:/data/registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data/registry
      - REGISTRY_HTTP_SECRET=qnap-sw2-registry
      - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis
      - REGISTRY_REDIS_ADDR=cache:6379

  cache:
    image: redis:4.0

volumes:
  registry-data:
