version: '3'

services:
  db:
    image: postgres:10
#    volumes:
#      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  
  web:
    depends_on:
      - db
    image: odoo:12.0
    ports:
      - "18069:8069"

#volumes:
#  db_data:
